Add : KakaoLogInView
wecode-bootcamp-korea/26-2nd-Prep-backend pull request #5
Opened 2021-11-19 09:35 UTC by DrageonLee

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- KakaoLogInView 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. Social Log In View 구현

2. Unittest 진행
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2021-11-19 09:54 UTC, Kang-kyunghun requested changes

2021-11-19 09:54 UTC, Kang-kyunghun commented on users/views.py
> +            print(profile_information_json)
print 지워주세요.

2021-11-19 09:54 UTC, Kang-kyunghun commented on users/views.py
> +            )
requests 모듈을 사용하실 때에는 timeout 옵션을 반드시 설정해주셔야 합니다.
그 이유는 timeout option을 추가하지 않으면 서버의 응답을 계속해서 기다리고 있는 문제가 발생 합니다. timeout 옵션을 추가해 주세요.
```suggestion
            profile_information = requests.get(
                "https://kapi.kakao.com/v2/user/me",
                headers = {'Authorization' : f'Bearer {ACCESS_TOKEN}'},
                timeout=5
            )
```

2021-11-19 09:54 UTC, Kang-kyunghun commented on users/views.py
> +            siteToken         = jwt.encode({"id" : user.id}, settings.SECRET_KEY, algorithm=settings.ALGORITHM)
변수 명은 카멜케이스로 바꿔주세요. site_token보다는 jwt_token이나 조금 더 다른 변수명이 나을 것 같아요.

2021-11-19 09:54 UTC, Kang-kyunghun commented on users/views.py
> +                return JsonResponse({"Token" : siteToken}, status = 200)
프론트에서 계정이 새로 생겼을 때랑 그냥 로그인 했을 때랑 액션이 다른가요?? 다르다면 
```suggestion
            if created: 
                return JsonResponse({"Token" : siteToken}, status = 201)
            
            return JsonResponse({"Token" : siteToken}, status = 200)
```
다르지 않으면 통일 시켜주세요.
```suggestion
             
            return JsonResponse({"Token" : siteToken}, status = 200)
```

2021-11-19 09:54 UTC, Kang-kyunghun commented on users/views.py
> +            return JsonResponse({"message" : "This access token does not exist"}, status = 401)
key에러는 값이 없다는 의미보다 정말 key가 잘 못 된 것이기 때문에 다음과 같이 수정해 주세요.
```suggestion
            return JsonResponse({"message" : "key error"}, status = 401)
```

2021-11-19 09:54 UTC, Kang-kyunghun commented on users/tests.py
> +from .models import User
wecode import 규칙에 맞게 작성해 주세요.

2021-11-19 09:54 UTC, Kang-kyunghun commented on users/tests.py
> +        User.objects.create(id=1, social_id = 1234567, nickname='hi', profile_image = "http://yyy.kakao.com/dn/.../img_640x640.jpg", email="drageon@gmail.com")
가독성 높여 주세요.
```suggestion
        User.objects.create(
            id=1, social_id = 1234567, 
            nickname='hi', 
            profile_image = "http://yyy.kakao.com/dn/.../img_640x640.jpg", 
            email="drageon@gmail.com"
        )
```

2021-11-19 09:54 UTC, Kang-kyunghun commented on users/tests.py
> +        siteToken           = jwt.encode({"id" : 1}, settings.SECRET_KEY, algorithm=settings.ALGORITHM)
변수명 카멜케이스로 바꿔주세요.

2021-11-19 09:54 UTC, Kang-kyunghun commented on users/tests.py
> +        self.assertEqual(response.status_code, 401)
json 결과도 추가해 주세요.

2021-11-19 09:54 UTC, Kang-kyunghun commented on users/tests.py
> +        siteToken           = jwt.encode({"id" : '1'}, settings.SECRET_KEY, algorithm=settings.ALGORITHM)
```suggestion
        response  = client.get("/users/kakao", **headers)
        siteToken = jwt.encode({"id" : '1'}, settings.SECRET_KEY, algorithm=settings.ALGORITHM)
```

2021-11-19 09:54 UTC, Kang-kyunghun commented on users/views.py
> +            profile_information = requests.get(
kakao로부터 항상 올바른 응답(200)을 받는다는 보장은 없습니다. 카카오로부터 에러코드를 받을 경우에 대해서 어떻게 처리해야 할지 생각해보고 코드에 예외처리 추가해 주세요.

2021-11-19 09:55 UTC, Kang-kyunghun commented
1. 통신 결과 첨부해 주세요.
2. 테스트 결과 첨부해 주세요.

2021-11-19 09:58 UTC, DrageonLee commented on users/views.py
> +            print(profile_information_json)
삭제 하였습니다.

2021-11-20 09:00 UTC, DrageonLee commented on users/views.py
> +            )
timeout option 추가 했습니다.

2021-11-20 09:45 UTC, DrageonLee commented on users/views.py
> +                return JsonResponse({"Token" : siteToken}, status = 200)
액션 하나로 통일하였습니다.

2021-11-20 11:33 UTC, DrageonLee commented on users/views.py
> +            return JsonResponse({"message" : "This access token does not exist"}, status = 401)
Key error로 수정 하였습니다.

2021-11-20 11:33 UTC, DrageonLee commented on users/tests.py
> +        User.objects.create(id=1, social_id = 1234567, nickname='hi', profile_image = "http://yyy.kakao.com/dn/.../img_640x640.jpg", email="drageon@gmail.com")
가독성 높게 변경하였습니다.

2021-11-20 11:34 UTC, DrageonLee commented on users/tests.py
> +        self.assertEqual(response.status_code, 401)
json 결과 추가 하였습니다.

2021-11-20 11:35 UTC, DrageonLee commented on users/tests.py
> +        siteToken           = jwt.encode({"id" : '1'}, settings.SECRET_KEY, algorithm=settings.ALGORITHM)
headers = {}이 없으면 error가 나서 header={}은 유지 하였습니다.

2021-11-20 11:37 UTC, DrageonLee commented on users/tests.py
> +from .models import User
wecode import 규칙에 맞게 작성하였습니다.

2021-11-20 11:52 UTC, DrageonLee commented on users/tests.py
> +        siteToken           = jwt.encode({"id" : 1}, settings.SECRET_KEY, algorithm=settings.ALGORITHM)
camelcase로 변경하였습니다.

2021-11-20 11:53 UTC, DrageonLee commented on users/views.py
> +            siteToken         = jwt.encode({"id" : user.id}, settings.SECRET_KEY, algorithm=settings.ALGORITHM)
camelcase로 변경 및 jwt_token으로 변경 완료 하였습니다.

2021-11-20 11:54 UTC, DrageonLee commented on users/views.py
> +            profile_information = requests.get(
카카오로 부터 에러코드 받을 경우에 대해 'if not 'Authorization'' : 으로 추가하였습니다.

2021-11-23 10:42 UTC, lordmyshepherd approved these changes
LGTMm 🥰

2021-11-23 10:42 UTC, lordmyshepherd commented
리베이스해서 올려주세요~~

2021-11-23 11:26 UTC, DrageonLee commented
> 리베이스해서 올려주세요~~

2021-11-23 11:29 UTC, DrageonLee commented
Rebase 완료 하였습니다.

2021-11-23 12:02 UTC, merged